---
- name: load k8s modules
  blockinfile:
    path: /etc/modules-load.d/k8s.conf
    create: yes
    block: |
      overlay
      br_netfilter
  notify:
    - modprobe-overlay
    - modprobe-br_netfilter

- name: set k8s net config
  blockinfile:
    path: /etc/sysctl.d/k8s.conf
    create: yes
    block: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1
  notify: sysctl-system
    