---
- name: install docker
  hosts: all
  tasks:
    - name: install deps
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release

    - name: create keyrings dir
      file:
        path: /etc/apt/keyrings/docker.gpg
        state: absent

    - name: remove gpg key
      file:
        path: /etc/apt/keyrings

    - name: add gpg key
      shell:
        cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg

    - name: get architecture
      shell: dpkg --print-architecture
      register: arch

    - name: delete repository
      file:
        path: /etc/apt/sources.list.d/docker.list
        state: absent

    - name: add repository
      apt_repository:
        filename: docker
        repo: deb [arch={{ arch.stdout }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
      become: yes

    - name: install docker
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - docker-ce={{ version}}
        - docker-ce-cli={{ version }}
        - containerd.io
        - docker-compose-plugin
